[tool.ruff]
builtins = [
    "_",
    "ngettext",
    "pgettext",
    "npgettext",
]
[tool.ruff.lint]
select = ["E4", "E7", "E9", "F"]
ignore = ["N802", "N803"]

[tool.ruff.lint.per-file-ignores]
# sconstruct contains many inbuilt functions not recognised by the lint,
# so ignore F821.
"sconstruct" = ["F821"]
